version: "3"

services:
  redis:
    image: redis

  worker:
    image: docker.io/brapper13/helloworld-python
    expose:
      - "8080"
    privileged: yes
    environment:
      - FUNCTION_STORAGE=fileserver
      - FILESERVER_URL=http://upload:8002
      - LOG_LEVEL=info
      - REDIS_HOST=redis

  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/conf/nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
    ports:
      - "8080:8080"