version: "3"

services:
  redis:
    image: docker.io/brapper13/redis

  worker:
    image: docker.io/brapper13/helloworld-python
    depends_on:
      - redis  
    expose:
      - "8080"
    privileged: yes
    environment:
      - FUNCTION_STORAGE=fileserver
      - FILESERVER_URL=http://upload:8002
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis
      - IN_CONTAINER=True
      - USE_SCHEDULER=True
    deploy:
      resources:
        limits:
          memory: 350M
          cpus: '0.8'
      
  data:
    image: docker.io/brapper13/populate
    depends_on:
      - redis  
    privileged: yes
    environment:
      - REDIS_HOST=redis

  nginx:
    image: nginx:latest
    volumes:
      - ./deploy/conf/nginx-local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
    ports:
      - "8080:8080"